services:
  backend:
    container_name: yewtrack-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    pull_policy: never
    image: yewtrack-backend
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - yewtrack-network
    environment:
      - NODE_ENV=production

  frontend:
    container_name: yewtrack-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    pull_policy: never
    image: yewtrack-frontend
    restart: unless-stopped
    ports:
      - "8041:80"
    depends_on:
      - backend
    networks:
      - yewtrack-network

networks:
  yewtrack-network:
    driver: bridge
